version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier

  result:
    build: ./result
    command: nodemon --debug server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - back-tier

  worker:
    build: ./worker
    networks:
      - front-tier
      - back-tier

  redis:
    image: azuredevops101.azurecr.cn/redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - front-tier

  db:
    image: azuredevops101.azurecr.cn/postgres:9.4
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
