apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-stack-k8s.yml
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - image: {acr-address}/postgres:9.4
        name: db
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: "trust"
        imagePullSecrets:
      - name: regcred
      restartPolicy: Always
status: {}
